services:
  postgres:
    container_name: prova-backend-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: prova-backend
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  nestjs:
    container_name: prova-fundamentos
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    entrypoint: ["sh", "-c", "npx prisma migrate deploy && node dist/main"]
    restart: on-failure
